export const policyRules = {
  metadata: {
    department: "Orlando Fire Department",
    version: "1.0",
    lastUpdated: "2026-04-02",
  },

  rules: [
    {
      id: "go63_training_oos_limit",
      category: "OOS Limits",
      topic: "Training OOS Limit",
      rule: "For training purposes, the maximum number of apparatus OOS is 3 engines, 2 truck companies, and 1 rescue. This maximum may be exceeded only with FROB Deputy Chief approval and adequate move-ups.",
      source: "GO 63",
      reference: "3.2-3.3",
      keywords: ["training", "oos", "engines", "trucks", "rescue", "approval", "move-up"],
    },
    {
      id: "go63_leave_first_due",
      category: "Movement",
      topic: "Leaving First Run Territory",
      rule: "Units will not leave first run territory on a non-emergency basis unless specifically authorized by the District Commander or above.",
      source: "GO 63",
      reference: "3.4.1",
      keywords: ["first run", "territory", "authorization", "district commander"],
    },
    {
      id: "go63_advise_comms",
      category: "Movement",
      topic: "Communications Notification",
      rule: "When a unit leaves first run territory, Communications must be advised of the territory they are in and their unit availability.",
      source: "GO 63",
      reference: "3.4.1.1",
      keywords: ["communications", "availability", "territory"],
    },
    {
      id: "ao22_short_term_window",
      category: "Staffing",
      topic: "Short-Term Staffing Window",
      rule: "Short-term reduced staffing is when normal staffing is expected to return within 4 hours.",
      source: "AO 22",
      reference: "3.1",
      keywords: ["4 hours", "short term", "staffing"],
    },
    {
      id: "ao22_truck_floor",
      category: "Staffing",
      topic: "Truck Minimum Staffing",
      rule: "Truck companies may be reduced to 3 persons for up to 4 hours. Below 3 persons they go OOS. At least 2 truck companies must remain at normal staffing at all times.",
      source: "AO 22",
      reference: "3.1.1",
      keywords: ["truck", "3 persons", "oos", "minimum staffing"],
    },
    {
      id: "ao22_4person_als_engine_floor",
      category: "Staffing",
      topic: "4-Person ALS Engine Staffing",
      rule: "4-person ALS engines may be reduced to 3 persons for up to 4 hours. Below 3 persons they go OOS.",
      source: "AO 22",
      reference: "3.1.2",
      keywords: ["als engine", "4 person", "3 persons", "oos"],
    },
    {
      id: "ao22_3person_als_engine_floor",
      category: "Staffing",
      topic: "3-Person ALS Engine Staffing",
      rule: "3-person ALS engines go OOS if staffing is reduced to 2 persons.",
      source: "AO 22",
      reference: "3.1.3",
      keywords: ["3 person engine", "2 persons", "oos"],
    },
    {
      id: "ao22_rescue_floor",
      category: "Staffing",
      topic: "Rescue Staffing",
      rule: "Rescue companies go OOS if staffing is reduced to 1 person.",
      source: "AO 22",
      reference: "3.1.4",
      keywords: ["rescue", "1 person", "oos"],
    },
    {
      id: "ao22_hr1_floor",
      category: "Staffing",
      topic: "Heavy Rescue Staffing",
      rule: "Heavy Rescue may be reduced to 4 persons for up to 4 hours. Below 4 persons it goes OOS.",
      source: "AO 22",
      reference: "3.1.5",
      keywords: ["heavy rescue", "4 persons", "oos", "hr1"],
    },
    {
      id: "ao22_moveup_factors",
      category: "Staffing",
      topic: "Move-Up Considerations",
      rule: "When satisfying staffing needs, the Assistant Chief should consider expertise, travel distance, and duration.",
      source: "AO 22",
      reference: "3.1.6",
      keywords: ["expertise", "travel", "duration", "move-up"],
    },
    {
      id: "ao22_long_term_ot",
      category: "Overtime",
      topic: "OT Trigger",
      rule: "If reduced staffing is expected to exceed 4 hours, normal overtime hiring procedures should be initiated.",
      source: "AO 22",
      reference: "3.2",
      keywords: ["overtime", "4 hours", "ot", "long term"],
    },
    {
      id: "ao52_hmt_units",
      category: "Special Operations",
      topic: "HMT Units",
      rule: "The Hazardous Materials Team is made up of E101, HazMat 1, and HMT tower trucks 7, 8, and 9.",
      source: "AO 52",
      reference: "2.3.1.1",
      keywords: ["hmt", "hazmat", "e101", "haz1", "tower 7", "tower 8", "tower 9"],
    },
    {
      id: "ao52_trt_units",
      category: "Special Operations",
      topic: "TRT Units",
      rule: "The Technical Rescue Team is HR1 and TRT tower trucks 1, 10, and 11.",
      source: "AO 52",
      reference: "2.3.2.1",
      keywords: ["trt", "hr1", "tower 1", "tower 10", "tower 11"],
    },
    {
      id: "ao52_e101_lead",
      category: "Special Operations",
      topic: "HazMat Lead Unit",
      rule: "E101 has the lead role on predominant hazardous materials incidents.",
      source: "AO 52",
      reference: "2.4.1",
      keywords: ["e101", "lead", "hazmat"],
    },
    {
      id: "ao52_hr1_lead",
      category: "Special Operations",
      topic: "TRT Lead Unit",
      rule: "HR1 has the lead role on predominant technical rescue incidents except for rope rescue and dive rescue, where the first TRT unit on scene leads.",
      source: "AO 52",
      reference: "2.4.3",
      keywords: ["hr1", "lead", "technical rescue", "rope", "dive"],
    },
    {
      id: "ao52_t1_dive_requirement",
      category: "Special Operations",
      topic: "T1 Dive Requirement",
      rule: "T1 is part of the OFD Dive Team and carries dive-related certifications and responsibilities.",
      source: "AO 52",
      reference: "2.5.2, 4.2.3.6",
      keywords: ["t1", "dive", "tower 1", "d certification"],
    },
    {
      id: "ao52_hr1_dive_requirement",
      category: "Special Operations",
      topic: "HR1 Dive Requirement",
      rule: "HR1 is part of the OFD Dive Team and carries dive-related certifications and responsibilities.",
      source: "AO 52",
      reference: "2.5.3, 4.2.2.6",
      keywords: ["hr1", "dive", "d certification"],
    },
    {
      id: "ao52_minimum_manning_special_ops",
      category: "Special Operations",
      topic: "Special Ops Minimum Manning",
      rule: "An effort should be made to maintain full manning on Special Operations units. Minimum manning is considered at least 3 paid members of the respective Special Operations team on each Special Operations unit.",
      source: "AO 52",
      reference: "5.1, 5.1.4",
      keywords: ["minimum manning", "special ops", "3 paid members"],
    },
    {
      id: "ao52_training_movement_rule",
      category: "Special Operations",
      topic: "Training Movement Rule",
      rule: "Minimum manning must still be observed when planning OFD training and other events that require personnel movement.",
      source: "AO 52",
      reference: "5.1.6",
      keywords: ["training", "personnel movement", "minimum manning"],
    },
    {
      id: "ao52_cross_shift_special_ops",
      category: "Special Operations",
      topic: "Cross-Shift Special Ops Staffing",
      rule: "Management may cross shift boundaries to fill Special Operations seat positions if no shift personnel meet the requirement. In OT mode, Special Operations team members are considered first when short of minimum manning.",
      source: "AO 52",
      reference: "5.1.1, 5.1.3",
      keywords: ["cross shift", "special ops", "overtime", "minimum manning"],
    },
    {
      id: "ao52_non_trt_on_t1_hr1",
      category: "Special Operations",
      topic: "Non-TRT Member on T1 or HR1",
      rule: "Any non-TRT member assigned on T1 or HR1 must be a Relief Driver and be checked off on dive boat, dive van, and dive tending operations by a Dive Team Leader.",
      source: "AO 52",
      reference: "5.1.7",
      keywords: ["non-trt", "t1", "hr1", "relief driver", "dive boat"],
    },
    {
      id: "ao52_hm1_driver_hmt",
      category: "Special Operations",
      topic: "HM1 Driver Requirement",
      rule: "The HM1 engineer or the person driving HM1 for the day must be a member of the HMT.",
      source: "AO 52",
      reference: "5.1.8",
      keywords: ["hm1", "driver", "hmt"],
    },
    {
      id: "ao52_letter_d",
      category: "Special Operations",
      topic: "Letter D",
      rule: "Letter D denotes a Dive Team member currently assigned to Tower 1 or Heavy Rescue and 2 alternates per shift receiving special teams pay.",
      source: "AO 52",
      reference: "5.2",
      keywords: ["letter d", "d", "dive"],
    },
    {
      id: "ao52_letter_h",
      category: "Special Operations",
      topic: "Letter H",
      rule: "Letter H denotes a Hazardous Materials Technician currently assigned to a HazMat Team unit and receiving special teams pay.",
      source: "AO 52",
      reference: "5.2",
      keywords: ["letter h", "h", "hazmat"],
    },
    {
      id: "contract_management_rights",
      category: "Contract",
      topic: "Management Rights",
      rule: "Management retains the right to establish and change work schedules, assignments, facility locations, and determine the number and types of positions assigned.",
      source: "IAFF Contract",
      reference: "Article 2 H, G",
      keywords: ["management", "assignments", "schedules", "facility locations"],
    },
    {
      id: "contract_staffing_safe",
      category: "Contract",
      topic: "Safe Staffing",
      rule: "Fire Department Management has a continuing responsibility to provide proper and safe staffing levels.",
      source: "IAFF Contract",
      reference: "Article 5",
      keywords: ["safe staffing", "proper staffing"],
    },
    {
      id: "contract_training_24hr_members",
      category: "Contract",
      topic: "Training for 24-Hour Members",
      rule: "24-hour combat members may be required to attend 8- or 10-hour training sessions. If this causes work in excess of normally scheduled hours for the biweekly period, overtime is due.",
      source: "IAFF Contract",
      reference: "Article 12.3",
      keywords: ["training", "24 hour", "8 hour", "10 hour", "overtime"],
    },
    {
      id: "contract_holiday_no_training",
      category: "Contract",
      topic: "Holiday Training Restriction",
      rule: "Combat members scheduled to work on a recognized holiday will not be required to participate in or attend training sessions on that holiday.",
      source: "IAFF Contract",
      reference: "Article 13.7",
      keywords: ["holiday", "training"],
    },
    {
      id: "contract_overtime_rule",
      category: "Contract",
      topic: "Overtime",
      rule: "Authorized and approved work beyond regularly scheduled hours in a two-week pay period is paid at one and one-half times the regular hourly rate.",
      source: "IAFF Contract",
      reference: "Article 16.1",
      keywords: ["overtime", "one and one-half", "two week pay period"],
    },
  ],
};
